name: myapp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0-209.1.beta

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.8
  cupertino_icons: ^1.0.8 
  google_fonts: ^6.2.1 
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.0.10
  flutter_map_marker_popup: ^6.1.2
  geolocator: ^9.0.1
  badges: ^2.0.1 
  flutter_rating_bar: ^4.0.0
  lucide_icons: ^0.257.0
  google_maps_flutter: ^2.1.1
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.14.0
  animations: ^2.0.7
  flutter_launcher_icons: ^0.13.1
  go_router: ^17.0.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/icones/

  # Si tu veux utiliser des polices personnalis√©es, ajoute-les ici :
  # fonts:
  #   - family: MyFont
  #     fonts:
  #       - asset: assets/fonts/MyFont-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true

